### ISSUE TITLE
issuecomment-536594689

### ISSUE THREAD

**Issue by DO1JLR** [maxbachmann-ansible/role-pihole#4]
https://github.com/maxbachmann-ansible/playbook-desktop/issues/2#issuecomment-536594689

Naja... Ich hatte dich mehrfach gebeten das irgendwo hin zu packen wo andere Menschen auch Zugriff haben und nicht in dein "privaten" homeordner...

Du sagtest... "Ja, gute Idee. Mach ich bald..."

Ist bis heute nicht erledigt...

Also hab ich das eben machen müssen!

**Comment by DO1JLR** [comment]
Das ist halt ein teil opensource code der zu kritisch ist um in einen privaten git-repo zu versauern oder plötzlich zu verschwinden!

**Comment by DO1JLR** [comment]
Und im gegensatz zu deinem kläglich fork versuch ist hier die history erhalten geblieben und deine commits wurden nicht gelöscht...

https://github.com/chaos-bodensee/lektor-scss/graphs/contributors

**Comment by maxbachmann** [comment]
das ist zwar zu einem anderen Repo aber ich hatte dich damals gefragt ob ich forken soll oder das selbst bei mir reinfügen soll. Und jetzt rat mal was deine Antwort war (kleiner Tipp es war nicht dass ich forken soll)
Ich habe auch gar kein Problem dass du das in chaos bodensee bewegt hast. Nur dass du dich dann über mein repo beschwerst bei dem du mir gesagt hast dass ich es so machen soll finde ich unschön. Abgesehn davon finde ich es natürlich auch recht unschön dass du meinst das dann mit deinem Spendenlink versehen zu müssen

**Comment by DO1JLR** [comment]
Scherzkeks, wie soll ich denn bri gelöschten Repos kommentieren?

Außerdem wird hier mehrere repos gemixt... 


Damals war die Frage das in meinem Repo mit zu pflegen oder das du dir das forkst und selber machst...

Und nein, bei mir machen hatte ich vin abgeraten... ist ja dein setup!
meins befundet sich auch bei mir privat und nicht bei chaos-bodensee

**Comment by DO1JLR** [comment]
Nicht zuelführend
